name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'package.json'
      - 'wrangler.toml'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Corepack
        run: |-
          npm install -g corepack
          corepack enable

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
